# Site settings
title: The little Ops
email: mini.inny@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  A geek, a photographer, a foodies, a traveller.
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: mini_inny
github_username:  innyso

# Build settings
markdown: kramdown
